export interface PhotoItem {
  id: string;
  title: string;
  category: "Cinematic" | "Street" | "Portrait" | "Urban" | "Experimental";
  year: string;
  camera: string;
  lens: string;
  settings: string;
  image: string;
  aspectRatio: "aspect-[4/5]" | "aspect-[16/9]" | "aspect-[3/4]" | "aspect-square";
  offset?: string; // CSS margin offset for asymmetric layout
}

export const PHOTOGRAPHY_ITEMS: PhotoItem[] = [
  {
    id: "photo-01",
    title: "NEON HORIZON // 01",
    category: "Cinematic",
    year: "2026",
    camera: "Sony A7IV",
    lens: "35mm f/1.4 GM",
    settings: "ISO 800 · f/1.8 · 1/500s",
    image: "/images/photography/photo-01.jpg",
    aspectRatio: "aspect-[4/5]",
    offset: "mt-0",
  },
  {
    id: "photo-02",
    title: "METROPOLIS PULSE // 02",
    category: "Urban",
    year: "2026",
    camera: "Fujifilm X-T5",
    lens: "23mm f/2",
    settings: "ISO 400 · f/2.8 · 1/1000s",
    image: "/images/photography/photo-02.jpg",
    aspectRatio: "aspect-[16/9]",
    offset: "md:mt-12",
  },
  {
    id: "photo-03",
    title: "CHROMA VELOCITY // 03",
    category: "Street",
    year: "2026",
    camera: "Sony A7IV",
    lens: "50mm f/1.2 GM",
    settings: "ISO 1600 · f/1.4 · 1/250s",
    image: "/images/photography/photo-03.jpg",
    aspectRatio: "aspect-[3/4]",
    offset: "md:-mt-6",
  },
  {
    id: "photo-04",
    title: "ANONYMOUS SHADOWS // 04",
    category: "Portrait",
    year: "2025",
    camera: "Sony A7IV",
    lens: "85mm f/1.4 GM",
    settings: "ISO 200 · f/2.0 · 1/2000s",
    image: "/images/photography/photo-04.jpg",
    aspectRatio: "aspect-[4/5]",
    offset: "md:mt-8",
  },
  {
    id: "photo-05",
    title: "KINETIC FREQUENCY // 05",
    category: "Experimental",
    year: "2026",
    camera: "Sony A7IV",
    lens: "24-70mm f/2.8",
    settings: "ISO 100 · f/8.0 · 1/60s",
    image: "/images/photography/photo-05.jpg",
    aspectRatio: "aspect-[16/9]",
    offset: "md:-mt-10",
  },
  {
    id: "photo-06",
    title: "CONCRETE MONOLITH // 06",
    category: "Urban",
    year: "2025",
    camera: "Fujifilm X100V",
    lens: "23mm f/2",
    settings: "ISO 1200 · f/2.0 · 1/125s",
    image: "/images/photography/photo-06.jpg",
    aspectRatio: "aspect-square",
    offset: "md:mt-6",
  },
  {
    id: "photo-07",
    title: "NIGHT EMBER // 07",
    category: "Street",
    year: "2026",
    camera: "Sony A7IV",
    lens: "35mm f/1.4 GM",
    settings: "ISO 3200 · f/1.4 · 1/160s",
    image: "/images/photography/photo-07.jpg",
    aspectRatio: "aspect-[4/5]",
    offset: "mt-0",
  },
  {
    id: "photo-08",
    title: "LUMEN ECHO // 08",
    category: "Cinematic",
    year: "2026",
    camera: "Sony A7IV",
    lens: "50mm f/1.2 GM",
    settings: "ISO 640 · f/2.0 · 1/800s",
    image: "/images/photography/photo-08.jpg",
    aspectRatio: "aspect-[16/9]",
    offset: "md:mt-10",
  },
  {
    id: "photo-09",
    title: "FRACTURED PERSPECTIVE // 09",
    category: "Experimental",
    year: "2025",
    camera: "Fujifilm X-T5",
    lens: "16-55mm f/2.8",
    settings: "ISO 250 · f/4.0 · 1/400s",
    image: "/images/photography/photo-09.jpg",
    aspectRatio: "aspect-[3/4]",
    offset: "md:-mt-8",
  },
  {
    id: "photo-10",
    title: "SILENT TRANSIT // 10",
    category: "Street",
    year: "2026",
    camera: "Sony A7IV",
    lens: "35mm f/1.4 GM",
    settings: "ISO 1000 · f/2.2 · 1/320s",
    image: "/images/photography/photo-10.jpg",
    aspectRatio: "aspect-[4/5]",
    offset: "md:mt-4",
  },
  {
    id: "photo-11",
    title: "GEOMETRIC DRIFT // 11",
    category: "Urban",
    year: "2026",
    camera: "Fujifilm X-T5",
    lens: "23mm f/2",
    settings: "ISO 400 · f/5.6 · 1/1250s",
    image: "/images/photography/photo-11.jpg",
    aspectRatio: "aspect-[16/9]",
    offset: "md:-mt-4",
  },
  {
    id: "photo-12",
    title: "PORTRAIT OF INTENT // 12",
    category: "Portrait",
    year: "2025",
    camera: "Sony A7IV",
    lens: "85mm f/1.4 GM",
    settings: "ISO 100 · f/1.8 · 1/1600s",
    image: "/images/photography/photo-12.jpg",
    aspectRatio: "aspect-[4/5]",
    offset: "md:mt-8",
  },
  {
    id: "photo-13",
    title: "CYBER DUSK // 13",
    category: "Cinematic",
    year: "2026",
    camera: "Sony A7IV",
    lens: "50mm f/1.2 GM",
    settings: "ISO 1600 · f/1.4 · 1/200s",
    image: "/images/photography/photo-13.jpg",
    aspectRatio: "aspect-[3/4]",
    offset: "mt-0",
  },
  {
    id: "photo-14",
    title: "STATIC DISSOLVE // 14",
    category: "Experimental",
    year: "2026",
    camera: "Sony A7IV",
    lens: "24-70mm f/2.8",
    settings: "ISO 800 · f/2.8 · 1/125s",
    image: "/images/photography/photo-14.jpg",
    aspectRatio: "aspect-square",
    offset: "md:mt-12",
  },
  {
    id: "photo-15",
    title: "SUBTERRANEAN GRID // 15",
    category: "Urban",
    year: "2025",
    camera: "Fujifilm X-T5",
    lens: "16-55mm f/2.8",
    settings: "ISO 640 · f/3.5 · 1/500s",
    image: "/images/photography/photo-15.jpg",
    aspectRatio: "aspect-[16/9]",
    offset: "md:-mt-6",
  },
  {
    id: "photo-16",
    title: "CHROMA SHIFT // 16",
    category: "Cinematic",
    year: "2026",
    camera: "Sony A7IV",
    lens: "35mm f/1.4 GM",
    settings: "ISO 1250 · f/1.6 · 1/400s",
    image: "/images/photography/photo-16.jpg",
    aspectRatio: "aspect-[4/5]",
    offset: "md:mt-6",
  },
  {
    id: "photo-17",
    title: "EDGE REFLECTION // 17",
    category: "Street",
    year: "2026",
    camera: "Fujifilm X100V",
    lens: "23mm f/2",
    settings: "ISO 800 · f/2.0 · 1/250s",
    image: "/images/photography/photo-17.jpg",
    aspectRatio: "aspect-[3/4]",
    offset: "md:-mt-8",
  },
  {
    id: "photo-18",
    title: "FINAL RESONANCE // 18",
    category: "Portrait",
    year: "2026",
    camera: "Sony A7IV",
    lens: "85mm f/1.4 GM",
    settings: "ISO 320 · f/1.8 · 1/1000s",
    image: "/images/photography/photo-18.jpg",
    aspectRatio: "aspect-[4/5]",
    offset: "md:mt-10",
  },
];
